services:
  ros2_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: robot-ros2-humble # resulting image name

    # container_name: dogsheep_ros2_devcontainer
    stdin_open: true
    tty: true
    command: /bin/bash # default shell when you attach
    network_mode: host # helps ROS 2 discovery (optional)

    privileged: true
    devices:
      - /dev:/dev

    # — Bind‑mount each git sub‑module into the workspace ————————————
    volumes:
      # - ../ros2_package:/home/ros/base_ws/src/:rw
      - ../ros2_package:/home/ros/base_ws/src/ros2_package:rw
      # - ./entry_script.sh:/home/ros/bash_scripts:rw
      # - ../submodules/sensors_src:/home/ros/sensors_ws/src:rw
      # - ../submodules/autonomy_src:/home/ros/autonomy_ws/src:rw
      # - ../submodules/control_src:/home/ros/control_ws/src:rw
      # - ../submodules/environment_src:/home/ros/environment_ws/src:rw

      # Bash Scripts
      - ../bash_scripts/container:/home/ros/bash_scripts:rw

      # Rosbag Storage
      # - ../rosbags:/home/ros/rosbags:rw

      # (Optional) keep colcon’s build artefacts outside the container
      # - colcon_cache:/home/ros/.colcon

      # enable mount for gui applications
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      - BASE_WS=/home/ros/base_ws
      # - SENSORS_WS=/home/ros/sensors_ws
      # - AUTONOMY_WS=/home/ros/autonomy_ws
      # - CONTROL_WS=/home/ros/control_ws
      # - ENVIRONMENT_WS=/home/ros/environment_ws
      # - BASH_SCRIPTS=/home/ros/bash_scripts
      # - ROSBAGS_DIR=/home/ros/rosbags
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1

volumes:
  colcon_cache:
######################################
# Robot_ROS2_Docker.git_template
# ./docker/[Dockerfile;docker-compose.yml]
# ./submodules/base_src/
# ./submodules/sensors_src/
# ./submodules/autonomy_src/
# ./submodules/control_src/
# ./submodules/environment_src/
# ./bash_scripts/container/[bashrc_extensions.sh]
# ./rosbags/

######################################
# Bunker_ROS2_Docker.git

# ./docker/Dockerfile
# ./docker/docker-compose.yml

# ./submodules/base_src/<agilex_ugv_drivers>
# ./submodules/base_src/<agilex_bunker_drivers>

# ./submodules/sensors_src/<mosaic_h_ros2>
# ./submodules/sensors_src/<realsense_sdk>
# ./submodules/sensors_src/<lora_ros2_bridge>

# ./submodules/autonomy_src/<autonomous_navigation_controller>

# ./submodules/control_src/<scheduling_manager>
# ./submodules/control_src/<archeology_msgs>

# ./submodules/environment_src/<environment_common>
# ./submodules/environment_src/<environment_template>

# ./bash_scripts/docker_functions.sh
# ./bash_scripts/bashrc_extensions.sh

# ./rosbags/rosbag_20240350.bag
